development:
  adapter: postgresql
  encoding: unicode
  database: mini_project
  pool: 5
  username: techstars
  password:

test:
 adapter: postgresql
 encoding: unicode
 database: mini_project
 pool: 5
 username: techstars
 password:

production:
 adapter: postgresql
 encoding: unicode
 database: mini_project
 pool: 5
 username: techstars
 password: